name: Auto Commit Dummy File

on:
  schedule:
    - cron: '0 0 * * *'    # setiap jam tepat UTC
  workflow_dispatch:      # bisa dijalankan manual

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Update dummy file
        run: |
          echo "Update: $(date -u)" >> dummy.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dummy.txt
          if ! git diff --cached --quiet; then
            git commit -m "Auto update dummy.txt @ $(date -u)"
            git push
          else
            echo "No changes to commit"
          fi

