name: Auto Commit Dummy File

on:
  schedule:
    - cron: '0 * * * *'    # setiap jam
  workflow_dispatch:      # bisa manual

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0               # <-- pastikan ini ada

      - name: Debug info
        run: |
          echo "=== Working directory ==="
          pwd
          echo "--- Listing files ---"
          ls -la
          echo "--- Git status & remote ---"
          git status
          git remote -v

      - name: Update dummy file
        run: |
          echo "Update: $(date -u)" >> dummy.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dummy.txt
          if ! git diff --cached --quiet; then
            git commit -m "Auto update dummy.txt @ $(date -u)"
            git push
          else
            echo "No changes to commit"
          fi
